version: 3.0.0.{build}
branches:
  only:
  - master
skip_tags: true
configuration: Release
environment:
  domain: https://disbott.uchuu.io
  twitter_consumer_key:
    secure: hu1J6bzZdF6BJ0rpR2gbW+WxNalzNuEWAQOaGVEjRMI=
  twitter_consumer_secret:
    secure: s75Lqzb+mDNy1XOORhs6lSdyE3+4GNN+ebSdPgLVBd+h5L2sxlohW+m7WfnXZNmRhTjqVs1ptQJuQGUsh/MIwg==
  twitter_access_token:
    secure: CgbHSQlIm9IYZEVJ+Qu00O6caATSO7zHpejsMF2OsC1D6+D+hKW1Oyupyv+f86V7mg0Ig0+9SXyHJMAWK90AGw==
  twitter_access_token_secret:
    secure: a1tfFnzEBvUL4Wkq3qAPjuz3XPciO29lziSXX8opNSlwwSx/x68QCGD9+LQaKu1B
  lol_api_key:
    secure: hexTPnjT1p/hz6lL2KtvI2dxuh6//M6mZpXh64Xutb93iXp0PEEEeqCobbQfkdAq
  token:
    secure: jWLMOGGxTzBlzWmt3MsKVc0wMU1E8Eh3jzEgBRdwkKfhuFtKvwZJvJEE3d2HbA+e12i0ISfX9Lx5gAR+eaeLhg==
  COVERALLS_REPO_TOKEN:
    secure: Bf2z3T/96DDM+4+IIRMoDQt96TUrAtHOxzQwFDKG9SnyPqxmB/MpWRo7kB/jVXqW
before_build:
- cmd: >-
    nuget sources add -Name DiscordNet -Source https://www.myget.org/F/discord-net/api/v3/index.json

    nuget restore
build:
  project: Disbott.sln
  publish_wap: true
  verbosity: minimal
after_test: 
    - packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -register:user -filter:"+[*]*" -target:"packages\NUnit.ConsoleRunner.3.5.0\tools\nunit3-console.exe" -targetargs:"/domain:single DisbottUnitTests\bin\Release\DisbottUnitTests.dll" -output:coverage.xml

    - packages\coveralls.io.1.3.4\tools\coveralls.net.exe --opencover coverage.xml
artifacts:
- path: Disbott\bin\Release
  name: azure
- path: Disbott\bin\Release\Disbott.exe
  name: github
deploy:
#- provider: GitHub
#  release: v$(appveyor_build_version)
#  auth_token:
#    secure: OKA6ofkLb6tShqWeYG1g2ywKFZxrU5cy6xlRfN2Uz4ETncetI7qMYpoHNsoQzDLS
#  artifact: github
#  draft: true
#  prerelease: true
#  force_update: false
- provider: AzureWebJob
  website: disbott
  username: $disbott
  password:
    secure: kAh3PlrZEjybpv2ZRsNu7CWk3VJkr2pl1P3jno+62m7kfQQT2Gh3N4RhhCexolxQjiomzMey/QVp5PfmK1NIYw==
  artifact: azure
  manually_triggered: true
notifications:
- provider: Slack
  incoming_webhook: https://discordapp.com/api/webhooks/256921709498728448/IMrXREwaISVnoPg_Ckod469Pqh1f1J4ayAFCgQRzJddcsAg58rg2RD-zyJKWu6lHBbN6/slack
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: false